### ISSUE TITLE
use share links instead?

### ISSUE THREAD

**Issue by felixroos** [mortuosplango/topfenstrudel#2]
I wonder how strudel pattern posts could be less annoying and still enjoyable for people that do not have this plugin.
One idea would be to detect share links instead of #strudel , like 

https://strudel.tidalcycles.org/?vBPJcewiHOq3

which could easily be detected + they are also clickable for the non plugin user. 
Additionally, it would be handy if the plugin only replaced the link and kept the text above and below as is, making it impossible accidentally post a repl with invalid code. With that, a pattern post would look totally normal for the average user..

This is how a post currently looks like:

![image](https://user-images.githubusercontent.com/12023032/210012094-ead2322b-3e79-4fe2-a479-8c0a51242448.png)

I actually needed a few attempts to get this right..

**Comment by felixroos** [comment]
btw I made the embedded repl a bit cleaner looking:

![image](https://user-images.githubusercontent.com/12023032/210012673-51a0536e-4fca-42fc-80a7-7971797b2781.png)

**Comment by mortuosplango** [comment]
Yeah, I think that's a great idea to detect share links. I would support both for now and see what sticks. Personally I find it interesting to read code in posts even if I can't execute it. Quite often I'm not likely to click a link, e.g. on my phone on the move, so I think having options is good, especially for long form code.

Also embedded repl looks great!

**Comment by mortuosplango** [comment]
Implemented in https://github.com/mortuosplango/topfenstrudel/releases/tag/1.1.0
